
export const upgrades = {};

upgrades["dmg1"] = {
    name: "Sharper Balls",
    id: "dmg1",
    previous: "",
    unlocked: false,
    function: "increaseDamage(game)",
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "Your balls do slightly more damage. Not much",
};
upgrades["dmg2"] = {
    name: "Flaming hot Balls",
    id: "dmg2",
    previous: "dmg1",
    unlocked: false,
    function: "increaseDamage(game)",
    costgray: 2,
    costyellow: 0,
    costblue: 0,
    description:
        "Adds a bit of heat. Still not enough to cook a steak, but it hurts.",
};
upgrades["dmg3"] = {
    name: "Cactus Balls",
    id: "dmg3",
    previous: "dmg2",
    unlocked: false,
    function: "increaseDamage(game)",
    costgray: 0,
    costyellow: 1,
    costblue: 0,
    description: "Now with spikes! Because why not make it more painful?",
};
upgrades["homing1"] = {
    name: "Self-Guided Nonsense",
    id: "homing1",
    previous: "dmg3",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 2,
    costblue: 0,
    description: "Your balls slightly curve towards enemies.",
};
upgrades["homing2"] = {
    name: "Aimbot",
    id: "homing2",
    previous: "homing1",
    unlocked: false,
    function: null,
    costgray: 4,
    costyellow: 2,
    costblue: 1,
    description:
        "Your projectiles now refuse to miss. Just don't get banned for hacking.",
};
upgrades["multishot1"] = {
    name: "Double Trouble",
    id: "multishot1",
    previous: "dmg3",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 1,
    costblue: 0,
    description:
        "Fire two shots instead of one. Twice the fun, twice the failure.",
};
upgrades["multishot2"] = {
    name: "Triple-shot",
    id: "multishot2",
    previous: "multishot1",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 2,
    costblue: 0,
    description: "Three shots. Because overkill is underrated.",
};
upgrades["bigball"] = {
    name: "Big Balls",
    id: "bigball",
    previous: "dmg2",
    unlocked: false,
    function: null,
    costgray: 0,
    costyellow: 0,
    costblue: 1,
    description: "Unlock special attack (Peircing ball)",
};
upgrades["dmgpercent5"] = {
    name: "Vampire Balls",
    id: "dmgpercent5",
    previous: "dmg1",
    unlocked: false,
    function: null,
    costgray: 5,
    costyellow: 0,
    costblue: 0,
    description: "Deal 5% of enemy hp as damage",
};
upgrades["dmgpercent20"] = {
    name: "Soul Siphoner",
    id: "dmgpercent20",
    previous: "dmgpercent5",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 1,
    costblue: 0,
    description: "Deal 20% of enemy hp as damage (replaces 5%)",
};
upgrades["hp1"] = {
    name: "Tougher Than Before",
    id: "hp1",
    previous: "",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "Gain an extra hit before you cry about it.",
};
upgrades["hp2"] = {
    name: "Tank Mode",
    id: "hp2",
    previous: "hp1",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 0,
    costblue: 0,
    description: "Increase health slightly",
};
upgrades["speed1"] = {
    name: "Still Slower Than a Snail",
    id: "speed1",
    previous: "",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description:
        "Marginally increases your speed. You *might* notice the difference.",
};
upgrades["speed2"] = {
    name: "Snail speed",
    id: "speed2",
    previous: "speed1",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 0,
    costblue: 0,
    description: "Increase move speed to a snail's pace.",
};
upgrades["speed3"] = {
    name: "Fast as lightning",
    id: "speed3",
    previous: "speed2",
    unlocked: false,
    function: null,
    costgray: 4,
    costyellow: 0,
    costblue: 0,
    description: "Increase move speed",
};
upgrades["speed4"] = {
    name: "Kinda fast now",
    id: "speed4",
    previous: "speed3",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 1,
    costblue: 0,
    description: "Increase move speed further.",
};
upgrades["speed5"] = {
    name: "Sonic But Legally Distinct",
    id: "speed5",
    previous: "speed4",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 2,
    costblue: 0,
    description: "Gotta go fast, but not too fast or Sega might sue.",
};
upgrades["speed6"] = {
    name: "Fast and Questionably Furious",
    id: "speed6",
    previous: "speed5",
    unlocked: false,
    function: null,
    costgray: 4,
    costyellow: 3,
    costblue: 1,
    description: "You're now legally classified as a hazard on the ground.",
};
upgrades["inventory1"] = {
    name: "Large bag",
    id: "inventory1",
    previous: "speed2",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "Fit more wealth in your pockets.",
};
upgrades["inventory2"] = {
    name: "Backpack",
    id: "inventory2",
    previous: "inventory1",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "Might have been a good idea to get this earlier.",
};
upgrades["timer1"] = {
    name: "More Time to Suffer",
    id: "timer1",
    previous: "speed1",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "Increase time limit",
};
upgrades["timer2"] = {
    name: "4 hours of sleep",
    id: "timer2",
    previous: "timer1",
    unlocked: false,
    function: null,
    costgray: 1,
    costyellow: 0,
    costblue: 0,
    description: "At least you have time to get things done",
};
upgrades["explosiveballs"] = {
    name: "Explosive Balls",
    id: "explosiveballs",
    previous: "bigball",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 1,
    costblue: 0,
    description: "Cannonballs explode on impact, dealing area damage.",
};
upgrades["dmg5"] = {
    name: "Frost Balls",
    id: "dmg5",
    previous: "explosiveballs",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 2,
    costblue: 0,
    description: "Slows enemies hit by the cannonball.",
};
upgrades["dmgnuke"] = {
    name: "Nuclear Balls",
    id: "dmgnuke",
    previous: "dmg5",
    unlocked: false,
    function: null,
    costgray: 5,
    costyellow: 3,
    costblue: 1,
    description: "Causes a massive explosion. Your enemies will *remember* this.",
};
upgrades["dmglightning"] = {
    name: "Lightning Balls",
    id: "dmglightning",
    previous: "explosiveballs",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 2,
    costblue: 0,
    description: "Chains to multiple enemies, dealing damage to all.",
};
upgrades["hp3"] = {
    name: "Iron Skin",
    id: "hp3",
    previous: "hp2",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 1,
    costblue: 0,
    description: "Reduce damage taken slightly.",
};
upgrades["hp4"] = {
    name: "Fortified Armor",
    id: "hp4",
    previous: "hp3",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 2,
    costblue: 0,
    description: "Further reduces damage taken.",
};
upgrades["regen1"] = {
    name: "Regeneration",
    id: "regen1",
    previous: "hp2",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 2,
    costblue: 0,
    description: "Slowly regenerates health over time.",
};
upgrades["regen2"] = {
    name: "Vampiric Regeneration",
    id: "regen2",
    previous: "regen1",
    unlocked: false,
    function: null,
    costgray: 4,
    costyellow: 2,
    costblue: 1,
    description: "Regenerate health when enemies are hit.",
};
upgrades["coffin"] = {
    name: "Discount Funeral Package",
    id: "coffin",
    previous: "hp1",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 0,
    costblue: 0,
    description:
        "Because you might not make it out alive. Comes with a budget tombstone. (Reduces death damage)",
};
upgrades["coffin2"] = {
    name: "Middle Class Coffin",
    id: "coffin2",
    previous: "coffin",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 2,
    costblue: 0,
    description: "Reduce death damage as much as your insurance allows",
};
upgrades["inventory3"] = {
    name: "Better Bag",
    id: "inventory3",
    previous: "inventory2",
    unlocked: false,
    function: null,
    costgray: 2,
    costyellow: 1,
    costblue: 0,
    description: "Increase inventory space further.",
};
upgrades["autocollect2"] = {
    name: "Super Magnet",
    id: "autocollect2",
    previous: "inventory2",
    unlocked: false,
    function: null,
    costgray: 5,
    costyellow: 3,
    costblue: 1,
    description: "Picks up items from a long distance.",
};
upgrades["timer3"] = {
    name: "Time Extender",
    id: "timer3",
    previous: "timer2",
    unlocked: false,
    function: null,
    costgray: 3,
    costyellow: 1,
    costblue: 0,
    description: "Further increases time limit.",
};
upgrades["timer4"] = {
    name: "Sun Dial",
    id: "timer4",
    previous: "timer3",
    unlocked: false,
    function: null,
    costgray: 4,
    costyellow: 2,
    costblue: 0,
    description: "Slows down time slightly.",
};
upgrades["timer5"] = {
    name: "Eternal Daylight",
    id: "timer5",
    previous: "timer4",
    unlocked: false,
    function: null,
    costgray: 5,
    costyellow: 3,
    costblue: 1,
    description: "Gain a permanent daytime extension.",
};
